using Libdl
libncurses = Libdl.dlopen("libncurses")
initscr() = ccall( Libdl.dlsym( libncurses, :initscr), Int32, () )
cbreak() = ccall( Libdl.dlsym( libncurses, :cbreak), Nothing, () )
nodelay(win,val) = ccall( Libdl.dlsym( libncurses, :nodelay), Nothing, (Int32,Int32),win,val)
noecho() = ccall( Libdl.dlsym( libncurses, :noecho), Nothing, () )
clear() = ccall( Libdl.dlsym( libncurses, :clear), Nothing, () )
printw(msg) = ccall( Libdl.dlsym( libncurses, :printw), Nothing, (Cstring,), msg )
mvprintw(y,x,msg) = ccall( Libdl.dlsym( libncurses, :mvprintw), Nothing, (Int32,Int32,Cstring,), y,x,msg )
getch() = ccall( Libdl.dlsym( libncurses, :getch), Int32, () )
endwin() = ccall( Libdl.dlsym( libncurses, :endwin), Nothing, () )
curs_set(i) = ccall( Libdl.dlsym( libncurses, :curs_set), Nothing, (Int32,),i)
refresh() = ccall( Libdl.dlsym( libncurses, :refresh), Nothing, () )
function getmaxyx(win)
    max_x = ccall( Libdl.dlsym( libncurses, :getmaxx), Int32, (Int32,),win)
    max_y = ccall( Libdl.dlsym( libncurses, :getmaxy), Int32, (Int32,),win)
    return (max_y,max_x)
end
